### ISSUE TITLE
Maven Import

### ISSUE THREAD

**Issue by Harvey-Mackie** [ErrorxCode/EasyInsta#11]
Is there any reason for this not to be accessible to download via Maven? 

## Repro Steps
- Added the following dependency to my Pom.xml file.
```
<dependency>
    <groupId>com.github.ErrorxCode</groupId>
    <artifactId>EasyInsta</artifactId>
    <version>2.7.2</version>
</dependency>
```

**Comment by ErrorxCode** [comment]
Can you please add the maven configuration (just like the gradle one) to the readme.md ? We would appreciate your contribution 💓
