### ISSUE TITLE
Android SDK Error

### ISSUE THREAD

**Issue by MuhammedAlmaz** [ErrorxCode/EasyInsta#13]
When i tried implement that dependency to my project, I am getting an error. The error, appears only when i run the application.

Error;
```
    class file has wrong version 60.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by ErrorxCode** [comment]
Just upgrade your java version. Download and install the latest JDK.

**Comment by MuhammedAlmaz** [comment]
I am not sure should i upgrade my java version. Because it is default option for Android Studio. I am using lastest Android Studio version.

**Comment by ErrorxCode** [comment]
> I am not sure should i upgrade my java version. Because it is default option for Android Studio. I am using lastest Android Studio version. 

In order to use latest JDK, your **gradle plugin must also be latest ( > 7.1)**, and for that, android studio should be too (> 4.0.x) .

I recommend you to update the **android studio** and your **Android gradle plugin** and then install latest supporting jdk manually on your system.

Then goto **File > Settings > Build tools > Gradle** and select that newly install jdk

**Comment by MuhammedAlmaz** [comment]
I upgraded my JAVA version i hope there are not any bug in the future :)

**Comment by ErrorxCode** [comment]
> > I am not sure should i upgrade my java version. Because it is default option for Android Studio. I am using lastest Android Studio version. 
> 
> In order to use latest JDK, your **gradle plugin must also be latest ( > 7.1)**, and for that, android studio should be too (> 4.0.x) .
> 
> I recommend you to update the **android studio** and your **Android gradle plugin** and then install latest supporting jdk manually on your system.
> 
> Then goto **File > Settings > Build tools > Gradle** and select that newly install jdk

Hope so. If you still having problem then contact me personally on instagram @x__coder__x

**Comment by ErrorxCode** [comment]
> I upgraded my JAVA version i hope there are not any bug in the future :)

Hope so. If you still having problem then contact me personally on [instagram @x__coder__x](https://Instagram.com/x__coder__x)
