### ISSUE TITLE
Is there a way to login with the proxy server?

### ISSUE THREAD

**Issue by GeorgiiFidarov** [ErrorxCode/EasyInsta#18]
So in the examples i saw how we can login, but this doesn't work for me.
As for instagram4j implementation we have a method .client inside the builder class. So it can login with proxy.

How can i do the same using you library?

**Comment by ErrorxCode** [comment]
Currently, you can't log in using a proxy. I could not successfully log in using proxy in Instagram4j too so I didn't implemented it here. _Will definitely check it again in next build_
