### ISSUE TITLE
[REQUEST] Pagination in fetching followers and followings

### ISSUE THREAD

**Issue by ErrorxCode** [ErrorxCode/EasyInsta#21]
Currently, We can only get top 100 followers/following of a account. I will implement **pagination** if I get enough support for this issue

**Comment by noirtier-villefort** [comment]
We need it! I remember that some solutions present in instagram4j issues or discord channel

**Comment by ErrorxCode** [comment]
This library will be re-written with the new API that is **on the way**. This feature might not be implemented in the first release but will be there in the future release. **Please have patience** till then

**Comment by ErrorxCode** [comment]
Addressed in #39
