### ISSUE TITLE
caching session on Android

### ISSUE THREAD

**Issue by krisbitney** [ErrorxCode/EasyInsta#23]
The session caching mechanism in this library is storing to the filesystem. It would be nice to have a login caching strategy that is secure for android apps.

It would be really nice if the `Instagram` constructor were public, so it would be easier to write a workaround

**Comment by ErrorxCode** [comment]
> It would be nice to have a login caching strategy that is secure for android apps.

What do you mean? please explain?

> so it would be easier to write a workaround

Why do you need a workaround? what's the problem ?

**Comment by krisbitney** [comment]
I'm new to android and was just confused by something. That's why I closed the issue. All is well!

**Comment by ErrorxCode** [comment]
Oh Ohk! No problem.



BTW, You can anytime contact me on my instagram **@x0.rahil** for any kind of help needed in this learning journey. I can even invite you to collab in my android projects which will give you more experience and knowledge.

_WELCOME TO ANDROID_ 💓
