### ISSUE TITLE
Bug, checking image extension when sending image message

### ISSUE THREAD

**Issue by ss-brandon** [ErrorxCode/EasyInsta#25]
Instagram.java

        public AsyncTask<Void> directMessage(@NotNull String username, @NotNull File photo) {
            if (!photo.getName().endsWith(".jpg") || !photo.getName().endsWith(".png") || !photo.getName().endsWith("jpeg"))
                throw new InstagramException("Unsupported file format. Only photos with jpg/png/jpeg extensions are allowed", Reasons.UNSUPPORTED_FILE_FORMAT);

             ....
        }
        
        ==> || to &&
        
         public AsyncTask<Void> directMessage(@NotNull String username, @NotNull File photo) {
            if (!photo.getName().endsWith(".jpg") && !photo.getName().endsWith(".png") && !photo.getName().endsWith("jpeg"))
                throw new InstagramException("Unsupported file format. Only photos with jpg/png/jpeg extensions are allowed", Reasons.UNSUPPORTED_FILE_FORMAT);

             ....
        }

**Comment by ErrorxCode** [comment]
Thanks for figuring out this bug. You should create a pull request editing the code yourself. Go ahead 👍🏻
