### ISSUE TITLE
How can I use Maven and Springboot to test the library

### ISSUE THREAD

**Issue by HenryGyu** [ErrorxCode/EasyInsta#28]
I want to deploy a springboot program on a Linux server to use the library, but I couldn't find the Maven configuration in the central repository

**Comment by ErrorxCode** [comment]
Step 1 : Add repository:-

	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

Step 2. Add the dependency

	<dependency>
	    <groupId>com.github.ErrorxCode</groupId>
	    <artifactId>EasyInsta</artifactId>
	    <version>2.9.2</version>
	</dependency>
