### ISSUE TITLE
Get posts by tag - Endpoint changed?

### ISSUE THREAD

**Issue by andor99** [ErrorxCode/EasyInsta#31]
Hello, I wanted to ask if you know the endpoint of getting the posts by providing a tag. I believe they recently changed it because it used to work with `https://i.instagram.com/api/v1/feed/tag/exampletag` but now it says "Page not found". Thanks!

**Comment by ErrorxCode** [comment]
### Posts by hashtag

API URL : `https://www.instagram.com/api/v1/tags/logged_out_web_info/?tag_name=coding`

**Required headers :-**
- `user-agent` =  `Instagram 244.0.0.17.110 Android`
- 

_No need login_
