### ISSUE TITLE
How can I research IG Realtime?

### ISSUE THREAD

**Issue by Yessirskiy** [ErrorxCode/EasyInsta#32]
If you guys could provide some sort of guide on how can we research Instagram MQTT traffic. I've succeed in sniffing HTTP traffic and requests to the common endpoints, but still cannot figure out how to intercept MQTToT traffic

**Comment by andor99** [comment]
One unrelated question, do you know which endpoint is to request posts for a given tag? It used to be "/feed/tag/exampletag". If you have a sniffing tool you can check it by tapping on a tag on an instagram post. Thanks!

**Comment by Yessirskiy** [comment]
> One unrelated question, do you know which endpoint is to request posts for a given tag? It used to be "/feed/tag/exampletag". If you have a sniffing tool you can check it by tapping on a tag on an instagram post. Thanks!

v1/tags/<exampletag>/sections/

**Comment by andor99** [comment]
> > One unrelated question, do you know which endpoint is to request posts for a given tag? It used to be "/feed/tag/exampletag". If you have a sniffing tool you can check it by tapping on a tag on an instagram post. Thanks!
> 
> v1/tags/exampletag/sections/

Hey thanks for your effort. Did you notice any other endpoints? Because this one doesn't return anything but also it doesn't say "Page not found". I guess it should include the "feed" keyword because we request posts.

**Comment by ErrorxCode** [comment]
> One unrelated question, do you know which endpoint is to request posts for a given tag? It used to be "/feed/tag/exampletag". If you have a sniffing tool you can check it by tapping on a tag on an instagram post. Thanks!

#31
