### ISSUE TITLE
[📢 Announcement ] The new library (API) is on the way  🛣️

### ISSUE THREAD

**Issue by ErrorxCode** [ErrorxCode/EasyInsta#33]
### [We are working on reverse engineering the Instagram API again](https://github.com/ErrorxCode/EasyInsta#announcement-) (but web this time)
A brand new library is been planed to be created as replacement of instagram4j. The new library will be more easy, optimised, and safe (less challenges) to use. The library will be based on the **privaye api of web version** of instagram. If you want to contribute on making of that new lib, please ping me at **@x0.rahil** on instagram. Little help is appreciated 💖

To get started, you need to discover/reverse engineer Instagram endpoints and add it to OpenAPI spec.json

#### Note : Until then, no updates will be pushed to _EasyInsta_ library and all the issue will be taken into account after the first release of that new instagram library

If you want to contribute but don't know what to do, drop "I WANNA HELP" in the reply of this issue and I will what you can do on your behalf.

Thank you,
~ Rahil (Lead developer)

**Comment by mdfarhananwar** [comment]
I WANNA HELP

**Comment by ErrorxCode** [comment]
> I WANNA HELP

Glad to see that. Can you please ping me at **x0.rahil** on instagram for a better conversation ?

**Comment by ErrorxCode** [comment]
The new library is now out
