### ISSUE TITLE
please add instagram live requests

### ISSUE THREAD

**Issue by hosseinziyaee** [ErrorxCode/EasyInsta#36]
Please add the methods related to creating a live stream, starting a live stream, and ending a live stream to the library. Thank you.

**Comment by ErrorxCode** [comment]
This library is migrating to a different library. All the further updates will be implemented in that library. Once it is out, I'll pin the link

**Comment by ErrorxCode** [comment]
The endpoints related to the live stream require camera support and captured data. Also, I don't see any practical application of those outside of official client. Hence they will not be implemented
