### ISSUE TITLE
[ FEATURE ⚡] Add support to Like/Dislike Posts

### ISSUE THREAD

**Issue by HectorHumanes** [ErrorxCode/EasyInsta#7]
Hi! First of all: many thanks for your effort on simplifiying the use of Instagram4J by this amazing library :)

It would be very much appreciated if you can consider to include a way to like and dislike posts.

Thank you very much!

**Comment by ErrorxCode** [comment]
Thanks for showing interest in my hard work. I will definitely add support for likes/dislikes in the next release (coming soon)
