### ISSUE TITLE
how to use callable

### ISSUE THREAD

**Issue by Hitexroid** [ErrorxCode/EasyInsta#8]
Hello there.
i really don't know how to put code from my editText to callable for Login2fatctor method.
please help.

thank you

**Comment by ErrorxCode** [comment]
**Login2fatctor** isn't yet supported by this library. You can't even use that on android using the original **insagram4j library** since there is no direct way to wait for the input on android.

However, there is a workaround which will be _implemented in the next release_ of **easyinsta**
